- name: Setup Apache web server
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Setup Apache
      import_role:
        name: apache2

    # - name: Check the welcome page
    #   shell: curl "{{ inventory_hostname }}" | grep 'title'
    #   register: result

    # - name: Display welcome page
    #   debug:
    #     msg: "{{ result.stdout_lines }}"
